// /app/layout.tsx
import './global.css';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { NextUIProvider } from '@nextui-org/react';
import { ReactQueryProvider } from './react-query-provider';
import 'react-datepicker/dist/react-datepicker.css';
import 'sweetalert2/src/sweetalert2.scss';

export const metadata = {
  title: 'vaquinha',
  description: 'Generated by create-solana-dapp',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider className="h-full">
          <ReactQueryProvider>
            <ClusterProvider>
              <SolanaProvider>{children}</SolanaProvider>
            </ClusterProvider>
          </ReactQueryProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
