import './global.css';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { UiLayout } from '@/components/layout/ui-layout';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { NextUIProvider } from '@nextui-org/react';
import { ReactQueryProvider } from './react-query-provider';
import 'react-datepicker/dist/react-datepicker.css';
import 'sweetalert2/src/sweetalert2.scss';

export const metadata = {
  title: 'vaquinha',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  { label: 'Join Group', path: '/groups' },
  { label: 'My Groups', path: '/my-groups' },
  { label: 'Profile', path: '/profile' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextUIProvider className="h-full">
          <ReactQueryProvider>
            <ClusterProvider>
              <SolanaProvider>
                <UiLayout links={links}>{children}</UiLayout>
              </SolanaProvider>
            </ClusterProvider>
          </ReactQueryProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
